// react/丁双/src/scripts/components/item/index.js

import {WhiteSpace,WingBlank} from "antd-mobile";
import {Link} from "react-router-dom";
export class Item extends Component{
    render(){
        const {good} = this.props;
        return (
            <div className = "move-in">
                <Link to = {"/good/detail/"+good._id+"?title="+good.type.text}>
                    <WingBlank>
                    <WhiteSpace/>
                    <img src={good.img} alt="" width = "100%" height = "280" style = {{borderRadius:"5px"}}/>
                    <h2 style = {{fontSize :"20px"}}>{good.title} -- {good.type.text}</h2>
                    <p style = {{fontSize:"22px",color:"red"}}>RMB:{good.price}元</p>
                    </WingBlank>
                </Link>
            </div>
        )
    }
}

// vue/胡奥/src/components/Item.vue
<template>
      <div class="item-move">
          <router-link :to="{name:'good',params:{goodId:good._id},query:{name:good.name}}" class="item">
         <van-card
            
            :price="good.price"
            :desc="good.type.text"  
            :title="good.name"
            :thumb="good.img"
            />
            <!-- <img :src="good.img" alt="" width="100%" height="240px">
            <h2>{{good.name}} ￥RMB{{good.price}}  {{good.type.text}}</h2> -->
     </router-link>
    </div>
</template>
<script>
export default {
     name:'item',
    props:['good']
}
</script>
<style scoped>
    h2{
        height: 45px;
        color: black;
        padding: 10px 0;
        font-size: 16px;
    }
    .item-move{
        animation: flipOutX .5s;
    }
</style>
