// react/李凯/src/scripts/components/uploadImg/index.js
import "./index.scss";
import React, { Component } from "react";
import { connect } from "react-redux";
import {upLoadImg1} from "../../react-redux/actions";

@connect(state => {
  return {
      userPic:state.data.userPic
  };
})
class UpLoadImg extends Component {
  kk() {
    console.log(this, this.refs.one);
    this.refs.one.click();
  }
  upload() {
    console.log("准备上传 ");
    console.log(this.props);
    let file = this.refs.one.files[0];
    let data = new FormData();
    data.append("avatar", file);
    var parent = {
      url: "/react-lyra/uploadAvatar",
      method: "POST",
      contentType: false,
      processData: false,
      data: data
    };
    this.props.dispatch(upLoadImg1(parent));
    // this.$store.dispatch("upload",parent);
    
  }

  componentWillMount() {}

  render() {
    console.log(typeof this);
    console.log(this.props)
    return (
      <div>
        <img
            width="80"
            height="80"
          onClick={() => {
            this.kk();
          }}
          src={localStorage.userPic?localStorage.userPic:require("@/assets/images/ajax-loader.gif")}
          alt=""
        />
        <input
          type="file"
          ref="one"
          accept="image/*"
          onChange={() => {
            this.upload();
          }}
          style={{ display: "none" }}
        />
      </div>
    );
  }
}

export default UpLoadImg;

// vue/胡奥/src/components/uploadimg.vue
<template>
    <div>
        <div id="photo">
            <img :src="txiang" alt="上传头像" @click.stop="uploadimg" class="tx">
            <input type="file" ref="one" accept="image/*" @change="updata" class="hiddenput">
        </div>
    </div>
</template>
<script>
export default {
    name:"avatar",
    data(){
        return{
            txiang:require('@/assets/images/Pikachu.jpg'),
        } 
    },
     methods:{
        uploadimg(){
            this.$refs.one.click();
        },
        updata(){
            let file = this.$refs.one.files[0];
            let data = new FormData();
            data.append("avatar",file);

            this.$axios({
                url:"/vue/uploadAvatar",
                method:"POST",
                contentType:false,
                processData:false,
                data:data,
            }).then(res=>{
                this.txiang = res.data.avatarurl.replace(/public/,"");
            })
            
        }
    }
    
}
</script>
<style scoped>
    .tx{
        width: 1rem;
        height: 1rem;
        border-radius: 50%;
    }
    .hiddenput{
        display: none;
    }
</style>
