// vue/孙权元/src/components/Foot.vue
<template>
    <div>
        <van-tabbar v-model="active">
            <van-tabbar-item v-for="(foot,i) in foots" :key="i" :name="foot.name">
            <i class="icon iconfont" v-html="foot.icon"></i>
            <p>{{foot.txt}}</p>
            </van-tabbar-item>
        </van-tabbar>
    </div>
</template>

<script>
export default {
    name:"Foot",
    computed:{
        
    },
    data(){
        return {
            
             foots:[
                {txt:"首页",path:"/index/home",name:"home",icon:"&#xe62a;"},
                {txt:"分类",path:"/index/classify",name:"classify",icon:"&#xe778;"},
                {txt:"购物车",path:"/index/cart",name:"cart",icon:"&#xe614;"},
                {txt:"我",path:"/index/my",name:"my",icon:"&#xe60c;"}
            ],
        }
    },
    computed:{
        active:{
            get(){
                return this.$store.state.active
            },
            set(val){
                //this.$store.state.active = this.$route.name;
                this.$store.state.active = val
                this.$router.push({name:val})
            }
        }
    },
    watch:{
        active(val){
             this.$store.state.active = val
        }
    }
    
}



</script>

// react/丁双/src/scripts/components/foot/index.js
 
import "./index.scss";

import {NavLink} from "react-router-dom";
import {Badge} from "antd-mobile";
export const foots = [
    {txt:"首页",path:"/app/home",name:"home",icon:"icon-01"},
    {txt:"分类",path:"/app/classify",name:"classify",icon:"icon-leimupinleifenleileibie"},
    {txt:"购物车",path:"/app/cart",name:"cart",icon:"icon-cart"},
    {txt:"我",path:"/app/my",name:"my",icon:"icon-iconfront-"}
];
export class Foot extends Component{
     state = {
        foots
     }
     render(){
         const {foots} = this.state;
         return (
             <footer>
                 {
                     foots.map((foot,i)=>{
                         return (
                             <div key = {i}>
                                 <NavLink to = {foot.path} activeClassName = "nav-active">
                                    <i className = {"iconfont icon "+foot.icon}></i>
                                    <span>{foot.txt}</span>
                                    {i==2&&<Badge className = "hot" text="10" style={{ marginLeft: 12 }}></Badge>}
                                 </NavLink>
                             </div>
                         )
                     })
                 }
             </footer>
         )
     }
 }
