// react/丁双/src/scripts/components/foot/index.js
 
import "./index.scss";

import {NavLink} from "react-router-dom";
import {Badge} from "antd-mobile";
export const foots = [
    {txt:"首页",path:"/app/home",name:"home",icon:"icon-01"},
    {txt:"分类",path:"/app/classify",name:"classify",icon:"icon-leimupinleifenleileibie"},
    {txt:"购物车",path:"/app/cart",name:"cart",icon:"icon-cart"},
    {txt:"我",path:"/app/my",name:"my",icon:"icon-iconfront-"}
];
export class Foot extends Component{
     state = {
        foots
     }
     render(){
         const {foots} = this.state;
         return (
             <footer>
                 {
                     foots.map((foot,i)=>{
                         return (
                             <div key = {i}>
                                 <NavLink to = {foot.path} activeClassName = "nav-active">
                                    <i className = {"iconfont icon "+foot.icon}></i>
                                    <span>{foot.txt}</span>
                                    {i==2&&<Badge className = "hot" text="10" style={{ marginLeft: 12 }}></Badge>}
                                 </NavLink>
                             </div>
                         )
                     })
                 }
             </footer>
         )
     }
 }

// vue/张伟杰/components/foot.vue
<template>
    <footer>
        <!-- <van-tabbar v-for="(foot,i) in foots" :key="i">
            <van-tabbar-item>
                <nuxt-link to="{name:foot.name}">
                    <i class="icon iconfont" v-html="foot.icon"></i>
                    <span>{{foot.text}}</span>
                </nuxt-link>
            </van-tabbar-item>
        </van-tabbar> -->


        <!-- <van-tabbar-item>标签</van-tabbar-item> -->
        <div>
            <van-tabbar v-model="active">
                <van-tabbar-item icon="home-o" name='home' to="/home">首页</van-tabbar-item>
                <van-tabbar-item icon="search" name="classify" to="/classify">分类</van-tabbar-item>
                <van-tabbar-item icon="friends-o" name="cart" to="/cart">购物车</van-tabbar-item>
                <van-tabbar-item icon="setting-o" name="my" to="/my">我</van-tabbar-item>
            </van-tabbar>
        </div>



    </footer>
</template>


<script>
    import { mapState, mapActions } from "vuex";
    export default {
        computed: {

            ...mapState(["active"]),

            active: {

                get() {
                    return this.$store.state.active
                },
                set(val) {

                    this.$store.commit("change", val)

                }
            }



        }



    }

</script>
