// vue/vue李凯/src/components/uploadImg.vue
<template>
  <div>
    <div>
      <img :src="userPic" alt="上传图片" @click.stop="uploadImg" class="userPic">
      <input type="file" ref="one" accept="image/*" @change="upload" style="display:none;">
    </div>
  </div>
</template>

<script>
export default {
    data(){
        return {
            // userPic: "",
        }
    },
    mounted() {
        // if(localStorage.userPic){
        //     this.userPic = localStorage.userPic;
        // }else{
        //     this.userPic = require("@/assets/images/duanwei.jpg");
        // }
    },
    computed: {
        userPic:{
            get(){
                // localStorage.userPic = this.$store.state.userPic;
                return this.$store.state.userPic;
            },
            set(val){
                return (this.$store.state.userPic = val)
            },
        }
    },
    methods: {
        uploadImg(){
            this.$refs.one.click(); // js中的 DOM 对象 click
        },
        upload(){
            // console.log("准备上传");
            // let file = this.$refs.one.files[0]; // 需要上传的 文件
            // let data = new FormData(); // 用js 新建一个表单对象    也可以html中 写 from标签

            // data.append("avatar",file);

            // this.$axios({
            //     url:"/lol/uploadAvatar",
            //     methods:"POST",
            //     contentType:false,
            //     processData:false,
            //     data:data
            // }).then(res=>{
            //     console.log(res);
            // })

            console.log("准备上传 ");
            let file = this.$refs.one.files[0];   
            let data = new FormData();   
            data.append("avatar",file);

            // this.$axios({
            //     url:"/lol/uploadAvatar",
            //     method:"POST",
            //     contentType:false,
            //     processData:false,
            //     data:data
            // }).then(res=>{
            //     console.log(res);
            //     this.userPic = res.data.avatarurl.replace(/public/,'http://localhost:2333/');
            //     localStorage.userPic = this.userPic;
            // })

            var parent ={
                url:"/lol/uploadAvatar",
                method:"POST",
                contentType:false,
                processData:false,
                data:data
            };
            this.$store.dispatch("upload",parent);


        }
    },
}
</script>

<style lang="scss" scoped>
.userPic {
  width: 1.8rem;
  height: 1.8rem;
  border-radius: 50%;
  margin: 0 auto;
}
</style>

// react/李凯/src/scripts/components/uploadImg/index.js
import "./index.scss";
import React, { Component } from "react";
import { connect } from "react-redux";
import {upLoadImg1} from "../../react-redux/actions";

@connect(state => {
  return {
      userPic:state.data.userPic
  };
})
class UpLoadImg extends Component {
  kk() {
    console.log(this, this.refs.one);
    this.refs.one.click();
  }
  upload() {
    console.log("准备上传 ");
    console.log(this.props);
    let file = this.refs.one.files[0];
    let data = new FormData();
    data.append("avatar", file);
    var parent = {
      url: "/react-lyra/uploadAvatar",
      method: "POST",
      contentType: false,
      processData: false,
      data: data
    };
    this.props.dispatch(upLoadImg1(parent));
    // this.$store.dispatch("upload",parent);
    
  }

  componentWillMount() {}

  render() {
    console.log(typeof this);
    console.log(this.props)
    return (
      <div>
        <img
            width="80"
            height="80"
          onClick={() => {
            this.kk();
          }}
          src={localStorage.userPic?localStorage.userPic:require("@/assets/images/ajax-loader.gif")}
          alt=""
        />
        <input
          type="file"
          ref="one"
          accept="image/*"
          onChange={() => {
            this.upload();
          }}
          style={{ display: "none" }}
        />
      </div>
    );
  }
}

export default UpLoadImg;
