// vue/董涛/src/views/classify.vue
<template>
    <div v-if="show">
        <Head title="商品分类"  ></Head>
        <van-tabs sticky animated>
            <van-tab :id="type.value" v-for="(type,i) in types" :title="type.text" :key="i">
                <List
                :type="type"
                :allGoods="allGoods"
                :goods="allGoods.filter(item=>item.type.value==type.value)"
                @changegoods="getAllGoods"
                ></List>
            </van-tab>
        </van-tabs>
        <!-- <mt-navbar v-model="selected">
            <mt-tab-item :id="type.value" v-for="(type,i) in types" :key="i"> {{type.text}}</mt-tab-item>
        </mt-navbar>    

        <mt-tab-container v-model="selected">
            <mt-tab-container-item :id="type.value" v-for="(type,i) in types" :key="i">
                <List
                    :type="type"
                    :allGoods="allGoods"
                    :goods="allGoods.filter(item=>item.type.value==type.value)"
                > </List>
            </mt-tab-container-item >
        </mt-tab-container> -->


    </div>
</template>

<script>
// import List from "@/components/List1.vue"
export default {
    name:"classify",
    // components:{
    //     List,
    // },
    data(){
        return{
            types:[],
            allGoods:[],
            show:false,
            selected:"cake"
        }
    },
    methods:{
        getAllGoods(){
            this.allGoods = this.allGoods.reverse();
        }
    },
    created(){
        this.$axios.get("/vue/getGoodTypes")
        .then(res=>{
            console.log(res);
            this.types = res.data.result;
        })

    },
    mounted(){
        this.$axios.get("/vue/getGoods",{
            params:{
                skip:11
            }
        })
        .then(res=>{
            console.log(res);
            this.allGoods = res.data.result;
            this.$nextTick(()=>{
                this.show = true;
            })
        })
        
    }
}
</script>

// react/丁双/src/scripts/views/classify/index.js


import "./index.scss";
import { Head } from "../../components/head/head";
import {connect} from "react-redux";
import { getAllGoods, getGoodTypes } from "../../actions";
import { GoodList } from "../../components/list";
import { Tabs, WhiteSpace, Badge } from 'antd-mobile';

@connect(
    state=>{
        return {
            types :state.data.types,
            allGoods :state.data.allGoods
        }
    }
)
export class Classify extends Component{

    componentWillMount(){
        const {types,dispatch,allGoods} = this.props;
        if(allGoods.length<=0){
            dispatch(getAllGoods({
                url:'/react/getGoods'
            }))
        }
     
        setTimeout(()=>{
            if(types&&types.length<=0){
                dispatch(getGoodTypes({
                    url:"/react/getGoodTypes"
                }))
            }
        },250)
        {
            types.map((item,i)=>{
                return (
                    item.title = item.text
                )
            })
        }
      
    }
    render(){
        // console.log("**")
        // console.log(this.props);
        const {types,allGoods} = this.props;
        
        // 筛选
        // const goods=allGoods.filter(item=>item.type.value == type.value);
        return (
            <div>
                <Head title = "分类"/>
                <Tabs tabs={types}
                    initialPage={0}
                    tabBarUnderlineStyle = {{border:"2px solid red"}}
                >
                    {
                        types&&types.map((type,i)=>{
                            return (
                                <GoodList key = {i} goods={allGoods.filter(item=>item.type.text == type.text  )}/>
                            )
                        })
                    }
                </Tabs>
            </div>
        )
    }
}
