// react/丁双/src/scripts/views/search/index.js
import { Head } from "../../components/head/head";

import {SearchBar} from "antd-mobile";
import {connect} from "react-redux";
import { getSearchGoods } from "../../actions";
import { GoodList } from "../../components/list";

@connect(
    state=>{
        return {
            searchGoods:state.data.searchGoods
        }
    }
)
export class Search extends Component{
    submit=(val)=>{
        console.log(val);
        const {dispatch} = this.props;
        dispatch(getSearchGoods({
            url:'/react/getGoods',
            params:{
                keyword:val
            }
        }))

    }
    change=(val)=>{
    }
    render(){
        // console.log("*********************");
       const {searchGoods} = this.props;
    //    console.log(searchGoods);
        return (
            <div>
                <Head title = "搜索" show = {true} search = {true}/>
                <SearchBar 
                placeholder="Search" 
                maxLength={8} 
                onSubmit = {this.submit}
                onChange = {this.change}
                />
                <GoodList
                goods = {this.props.searchGoods}
                />
            </div>
        )
    }
}

// vue/王行建/vue/src/views/search.vue
<template>
  <div>
    <Head title="搜索"></Head>
    <form action="/" v-if="flag" class="search">
      <van-search v-model="keyword" placeholder="请输入搜索关键词" show-action @cancel="onCancel"/>
    </form>
    <List :goods="data.searchGoods" v-if="keyword!==''"></List>
  </div>
</template>
<script>
import { mapState, mapActions } from "vuex";
export default {
  name: "search",
  data() {
    return {
      flag: true
    };
  },
  computed: {
    ...mapState(["data"]),
    keyword: {
      get() {
        return this.$store.state.keyword;
      },
      set(val) {
        this.$store.commit("getKeyword", val);
      }
    }
  },
  methods: {
    onCancel() {
      this.flag = !this.flag;
    },
    ...mapActions(["getSearchGoods"])
  },
  watch: {
    keyword(newVal) {
      this.getSearchGoods({
        url: "/vue/getGoodsData",
        params: {
          keyword: newVal
        }
      });
    }
  }
};
</script>
<style scoped>
.search {
  margin-top: 0.8rem;
}
</style>
