// vue/董涛/src/views/search.vue
<template>
    <div>
        <Head title="搜索" :show="true" ></Head>
        <van-search placeholder="请输入搜索关键词" v-model.lazy="keyword" show-action/>
        <List :goods="goods"  @changegoods="getNewGoods">
            
        </List>
    </div>
</template>


<script>
export default {
    name:"search",
    data(){
        return{
            keyword:"",
            goods:[]
        }
    },
    methods:{
        getNewGoods(data){
            console.log(data);
            this.goods = data;
        }
    },
    watch:{
        keyword(newVal){
            console.log(newVal);
            this.$axios.get("/vue/getGoods",{
                params:{
                    keyword:newVal
                }
            }).then(res=>{
                this.goods  = res.data.result;
                console.log(res);
            })
        }
    }
}
</script>

// react/丁双/src/scripts/views/search/index.js
import { Head } from "../../components/head/head";

import {SearchBar} from "antd-mobile";
import {connect} from "react-redux";
import { getSearchGoods } from "../../actions";
import { GoodList } from "../../components/list";

@connect(
    state=>{
        return {
            searchGoods:state.data.searchGoods
        }
    }
)
export class Search extends Component{
    submit=(val)=>{
        console.log(val);
        const {dispatch} = this.props;
        dispatch(getSearchGoods({
            url:'/react/getGoods',
            params:{
                keyword:val
            }
        }))

    }
    change=(val)=>{
    }
    render(){
        // console.log("*********************");
       const {searchGoods} = this.props;
    //    console.log(searchGoods);
        return (
            <div>
                <Head title = "搜索" show = {true} search = {true}/>
                <SearchBar 
                placeholder="Search" 
                maxLength={8} 
                onSubmit = {this.submit}
                onChange = {this.change}
                />
                <GoodList
                goods = {this.props.searchGoods}
                />
            </div>
        )
    }
}
